//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_Profiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Code_Profiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;bits/stdc++.h&gt;
        ///
        ///const int TESTS = 10;
        ///
        ///void printArg(int tc){
        ///	printf(&quot;\n&quot;);
        ///}
        ///
        ///int main(){
        ///	printf(&quot;%d\n&quot;, TESTS);
        ///	for (int i = 0; i &lt; TESTS; i++)
        ///		printArg(i);
        ///}.
        /// </summary>
        internal static string cpp_driver {
            get {
                return ResourceManager.GetString("cpp_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;bits/stdc++.h&gt;
        ///#include &lt;random&gt;
        ///#include &lt;fstream&gt;
        ///
        ///using namespace std;
        ///typedef vector&lt;int&gt; vi;
        ///typedef long long ll;
        ///typedef unsigned long long ull;
        ///const long long INFl = (ll)1 &lt;&lt; 62;
        ///const int INF = 1 &lt;&lt; 30;
        ///
        ///int argl;
        ///char **arg;
        ///int getParam(const char *s){
        ///	for (int i = 1; i&lt;argl; i += 2){
        ///		if (!strcmp(s, arg[i]))
        ///			return atoi(arg[i + 1]);
        ///	}
        ///	cout &lt;&lt; s &lt;&lt; &quot; not found\n&quot;;
        ///}
        ///string RandomString(int len, string c){
        ///
        ///	string r = &quot;&quot;;
        ///	while (len--){
        ///		r += c[rand() % [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cpp_test {
            get {
                return ResourceManager.GetString("cpp_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTS=10
        ///def printArg(tc):
        ///    print &quot;\n&quot;
        ///print TESTS
        ///for i in range(0, TESTS):printArg(i).
        /// </summary>
        internal static string py_driver {
            get {
                return ResourceManager.GetString("py_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string text_driver {
            get {
                return ResourceManager.GetString("text_driver", resourceCulture);
            }
        }
    }
}
